import { Building, Newspaper, Beaker, Briefcase, Scale } from 'lucide-react';

export const sourceCategories = [
  {
    name: 'Government & Regulatory',
    description: 'Official government agencies and regulatory bodies',
    icon: Building,
    sources: [
      { title: 'CERT-In Advisory CIAD-2025-001', type: 'Official Report', url: '#' },
      { title: 'PIB Press Release', type: 'Official Report', url: '#' },
      { title: 'RBI Press Release', type: 'Official Report', url: '#' },
      { title: 'CERT-In Advisory on WannaCry', type: 'Official Report', url: '#' },
      { title: 'Microsoft Security Bulletin MS01-033', type: 'Official Report', url: '#' },
      { title: 'Microsoft Security Bulletin MS01-044', type: 'Official Report', url: '#' },
      { title: 'Bugbear Worm Analysis (Symantec)', type: 'Official Report', url: '#' },
      { title: 'Internet Attacks 2005 | Securelist', type: 'Official Report', url: '#' },
    ],
  },
  {
    name: 'News & Media',
    description: 'Reputable news organizations and technology publications',
    icon: Newspaper,
    sources: [
        { title: 'News reports from 2003', type: 'News Article', url: '#' },
        { title: 'The Hindu BusinessLine Report', type: 'News Article', url: '#' },
        { title: 'Livemint Report on SBI Phishing', type: 'News Article', url: '#' },
        { title: 'TechCrunch Exclusive on Justdial Leak', type: 'News Article', url: '#' },
        { title: 'Reuters Insight: The Cosmos Bank Heist', type: 'News Article', url: '#' },
        { title: 'HuffPost India Investigation', type: 'News Article', url: '#' },
        { title: 'The Hindu Report on SMS Ban', type: 'News Article', url: '#' },
        { title: 'The Hindu Confirms Malware Attack', type: 'News Article', url: '#' },
        { title: 'Frontline: The War Room Breach', type: 'News Article', url: '#' },
        { title: 'Both Sides Hacked Over Kashmir (Wired)', type: 'News Article', url: '#' },
        { title: 'TechCrunch Report on Cleartrip Breach', type: 'News Article', url: '#' },
        { title: 'India Today Report', type: 'News Article', url: '#' },
        { title: 'ZDNet Report on Indane Leak', type: 'News Article', url: '#' },
        { title: 'Economic Times Explainer', type: 'News Article', url: '#' },
        { title: 'Times of India Report', type: 'News Article', url: '#' },
        { title: 'The Hindu Report on AIIMS Attack', type: 'News Article', url: '#' },
        { title: 'Times of India Report', type: 'News Article', url: '#' },
        { title: 'The \'I Love You\' worm, 2000 coverage (The Guardian)', type: 'News Article', url: '#' },
        { title: 'Rediff: The Indian who fought \'I Love You\' (May 2000)', type: 'News Article', url: '#' },
        { title: 'Archived news of usinfo.state', type: 'News Article', url: '#' },
        { title: 'India Today (June 2001 retrospective mentioning Zee defacement in 2000)', type: 'News Article', url: '#' },
        { title: 'Times of India retrospective (mentions IISc incidents around 2000-2002)', type: 'News Article', url: '#' },
        { title: 'Pakistani hackers deface Indian sites', type: 'News Article', url: '#' },
        { title: 'Republic Day cyber attacks', type: 'News Article', url: '#' },
        { title: 'Hackers hit Indian Railways website', type: 'News Article', url: '#' },
        { title: 'India\'s foreign ministry web site hacked', type: 'News Article', url: '#' },
        { title: 'Pakistani group G-Force hacked MEA site', type: 'News Article', url: '#' },
        { title: 'Two suspects picked up for hacking into Bombay police web site', type: 'News Article', url: '#' },
        { title: 'India Hackers Scared Straight?', type: 'News Article', url: '#' },
        { title: 'Bugs, viruses & worms plague IT world', type: 'News Article', url: '#' },
        { title: 'Safe mail and worm attack — The Nimda worm', type: 'News Article', url: '#' },
        { title: 'New worm strikes: Little impact on India', type: 'News Article', url: '#' },
        { title: 'Police slap sedition charge on hackers', type: 'News Article', url: '#' },
        { title: 'Parliament attack: cyber forensics role', type: 'News Article', url: '#' },
        { title: 'India, Pakistan & Hacktivism – Past, Present & Future (Part One)', type: 'News Article', url: '#' },
        { title: 'Bugbear Worm Spreads Rapidly (BBC News, Oct 2002)', type: 'News Article', url: '#' },
        { title: 'IITian held for stealing software source code (Times of India, Aug 2002)', type: 'News Article', url: '#' },
        { title: 'India, Pak locked in cyber war (Times of India, Nov 2003)', type: 'News Article', url: '#' },
        { title: 'No-holds barred cyber war (Times of India, Nov 2003)', type: 'News Article', url: '#' },
        { title: 'Indo-Pak hackers battle in cyberspace', type: 'News Article', url: '#' },
        { title: 'SQL Slammer (Wikipedia)', type: 'News Article', url: '#' },
        { title: 'Blaster (computer worm) (Wikipedia)', type: 'News Article', url: '#' },
        { title: 'Now, viruses target ATMs (Times of India, Dec 2003)', type: 'News Article', url: '#' },
        { title: 'Sobig (Wikipedia)', type: 'News Article', url: '#' },
        { title: 'When worms strike (Times of India, Sep 2003)', type: 'News Article', url: '#' },
        { title: 'Which was the 1st cyber crime conviction in India? (Techshots)', type: 'News Article', url: '#' },
        { title: 'Juvenile faces trial in cyber-crime case (Times of India, Nov 2003)', type: 'News Article', url: '#' },
        { title: 'Fourth case of cyber crime; 3 booked (Times of India, Oct 2003)', type: 'News Article', url: '#' },
        { title: 'Timeline of computer viruses and worms (Wikipedia)', type: 'News Article', url: '#' },
        { title: 'Mydoom (Wikipedia)', type: 'News Article', url: '#' },
        { title: 'Sasser (computer worm) (Wikipedia)', type: 'News Article', url: '#' },
        { title: 'Sasser worm hits up to 1m computers (The Guardian)', type: 'News Article', url: '#' },
        { title: 'Suhas Katti v. Tamil Nadu (Wikipedia)', type: 'News Article', url: '#' },
        { title: 'BPO frauds', type: 'News Article', url: '#' },
        { title: 'India\'s first BPO scam unraveled', type: 'News Article', url: '#' },
        { title: 'Overview of famous cyber crime cases that target people instead of ...', type: 'News Article', url: '#' },
        { title: 'BPO fraud: another Rs 38 lakh traced | Pune News', type: 'News Article', url: '#' },
        { title: 'Pune call centre fraud rattles India\'s booming BPO sector, raises questions on security', type: 'News Article', url: '#' },
        { title: 'Zotob (computer worm) - Wikipedia', type: 'News Article', url: '#' },
        { title: 'Hackers - Hot Spot - 06: India - Siliconindia', type: 'News Article', url: '#' },
        { title: 'Indian cyberspace under attack - Rediff.com', type: 'News Article', url: '#' },
        { title: '400 Indian websites came under attack in Dec - The Economic Times', type: 'News Article', url: '#' },
        { title: 'BPO fraud unearthed at SlashSupport - Times of India', type: 'News Article', url: '#' },
        { title: 'BPO fraud unearthed at SlashSupport, Chennai - The Economic Times', type: 'News Article', url: '#' },
        { title: 'Do BPO frauds harm India\'s image? - Rediff.com', type: 'News Article', url: '#' },
        { title: 'Fraud arrest at HSBC\'s Indian call centre | Money - The Guardian', type: 'News Article', url: '#' },
        { title: 'HSBC BPO staff named in Rs 1.8 cr fraud - Business Standard', type: 'News Article', url: '#' },
        { title: 'Kama Sutra (computer worm) - Wikipedia', type: 'News Article', url: '#' },
    ],
  },
  {
    name: 'Research & Academic',
    description: 'Academic institutions and security research organizations',
    icon: Beaker,
    sources: [
        { title: 'Trend Micro Report on Operation Castling', type: 'Research Paper', url: '#' },
        { title: 'Resecurity Report', type: 'Research Paper', url: '#' },
        { title: 'Tracking GhostNet Report Summary', type: 'Research Paper', url: '#' },
        { title: 'ILOVEYOU (Wikipedia entry)', type: 'Research Paper', url: '#' },
        { title: 'Regional rivalry between India–Pakistan: tit-for-tat in cyberspace (ETH Zurich CSS report, 2018)', type: 'Research Paper', url: '#' },
        { title: 'The Spread of the Code-Red Worm (CAIDA)', type: 'Research Paper', url: '#' },
        { title: 'Security Implications for Wired India: Role of Technology', type: 'Research Paper', url: '#' },
        { title: 'The evolution of security: the story of Code Red', type: 'Research Paper', url: '#' },
        { title: 'The Nimda Worm: An Overview (SANS Institute)', type: 'Research Paper', url: '#' },
        { title: 'Whither Cyber Terror? (SSRC)', type: 'Research Paper', url: '#' },
        { title: 'Demystifying Data Breaches in India (Centre for Internet and Society)', type: 'Research Paper', url: '#' },
        { title: 'Cyber Warfare between Pakistan and India: Implications for the Region', type: 'Research Paper', url: '#' },
        { title: '20 Recent Cyber Attacks in India [2025] - Eventus Security', type: 'Research Paper', url: '#' },
        { title: 'The Nyxem Email Virus: Analysis and Inferences - CAIDA.org', type: 'Research Paper', url: '#' },
    ],
  },
  {
    name: 'Corporate & Vendor Reports',
    description: 'Disclosures from companies and security vendors',
    icon: Briefcase,
    sources: [
        { title: 'Zomato Blog Post on Breach', type: 'Company Disclosure', url: '#' },
        { title: 'Cyber Crime Case Studies (Cyber Law Asia)', type: 'Company Disclosure', url: '#' },
        { title: 'Cyber Crime Case Studies Ahmedabad :: Cyber Fraud In India', type: 'Company Disclosure', url: '#' },
        { title: 'Cyber Case Laws by Cyber Law Consulting', type: 'Company Disclosure', url: '#' },
        { title: 'State of Tamil Nadu vs Suhas Katti - Case Analysis', type: 'Company Disclosure', url: '#' },
        { title: 'Nasscom vs. Ajay Sood & Others', type: 'Company Disclosure', url: '#' },
    ],
  },
  {
    name: 'Legal & Court Documents',
    description: 'Official court filings and legal records',
    icon: Scale,
    sources: [
        { title: 'National Association Of Software And ... vs Ajay Sood And Ors. on 23 March, 2005', type: 'Court Filing', url: '#' },
    ],
  },
];
