
import { Building, Newspaper, Beaker, Briefcase, Scale } from 'lucide-react';

export const sourceCategories = [
  {
    name: 'Government & Regulatory',
    description: 'Official government agencies and regulatory bodies',
    icon: Building,
    sources: [
      { title: 'CERT-In Advisories', type: 'Official Report', url: 'https://www.cert-in.org.in/s2c/advisories.html' },
      { title: 'PIB Press Releases', type: 'Official Report', url: 'https://pib.gov.in/newsite/pressrelease.aspx' },
      { title: 'RBI Press Releases', type: 'Official Report', url: 'https://www.rbi.org.in/Scripts/PressReleases.aspx' },
      { title: 'CERT-In Advisory on WannaCry', type: 'Official Report', url: 'https://www.cert-in.org.in/s2c/2017/Cert-In_Advisory_20170513.pdf' },
      { title: 'Microsoft Security Bulletin MS01-033 (Code Red)', type: 'Official Report', url: 'https://learn.microsoft.com/en-us/security-updates/securitybulletins/2001/ms01-033' },
      { title: 'Microsoft Security Bulletin MS01-044 (Nimda)', type: 'Official Report', url: 'https://learn.microsoft.com/en-us/security-updates/securitybulletins/2001/ms01-044' },
      { title: 'Bugbear Worm Analysis (Symantec)', type: 'Official Report', url: 'https://www.broadcom.com/support/security-response/w32.bugbear.b-mm' },
    ],
  },
  {
    name: 'News & Media',
    description: 'Reputable news organizations and technology publications',
    icon: Newspaper,
    sources: [
        { title: 'The Hindu BusinessLine Report', type: 'News Article', url: 'https://www.thehindubusinessline.com/' },
        { title: 'Livemint Report on SBI Phishing', type: 'News Article', url: 'https://www.livemint.com/money/personal-finance/sbi-warning-beware-of-this-sms-phishing-scam-or-you-will-lose-your-money-11629087295739.html' },
        { title: 'TechCrunch Exclusive on Justdial Leak', type: 'News Article', url: 'https://techcrunch.com/2019/04/20/justdial-data-leak-100-million-users/' },
        { title: 'Reuters Insight: The Cosmos Bank Heist', type: 'News Article', url: 'https://www.reuters.com/investigates/special-report/cyber-heist-cosmos/' },
        { title: 'HuffPost India Investigation', type: 'News Article', url: 'https://www.huffingtonpost.in/news/cybersecurity/' },
        { title: 'The Hindu Confirms Malware Attack', type: 'News Article', url: 'https://www.thehindu.com/news/national/kudankulam-nuclear-power-plant-confirms-malware-attack-on-its-system/article29831006.ece' },
        { title: 'Both Sides Hacked Over Kashmir (Wired)', type: 'News Article', url: 'https://www.wired.com/2002/01/both-sides-hacked-over-kashmir/' },
        { title: 'TechCrunch Report on Cleartrip Breach', type: 'News Article', url: 'https://techcrunch.com/2022/07/18/india-cleartrip-customer-data-breach/' },
        { title: 'India Today Report', type: 'News Article', url: 'https://www.indiatoday.in/' },
        { title: 'ZDNet Report on Indane Leak', type: 'News Article', url: 'https://www.zdnet.com/article/indian-gas-company-leaks-aadhaar-data-on-millions-of-customers-again/' },
        { title: 'Economic Times Explainer', type: 'News Article', url: 'https://economictimes.indiatimes.com/' },
        { title: 'Times of India Report', type: 'News Article', url: 'https://timesofindia.indiatimes.com/' },
        { title: 'The Hindu Report on AIIMS Attack', type: 'News Article', url: 'https://www.thehindu.com/sci-tech/technology/aiims-server-hack-a-wake-up-call-for-indias-healthcare-sector/article66224160.ece' },
        { title: 'The \'I Love You\' worm, 2000 coverage (The Guardian)', type: 'News Article', url: 'https://www.theguardian.com/technology/2000/may/05/internetnews.guardianhayfestival2000' },
        { title: 'Rediff: The Indian who fought \'I Love You\' (May 2000)', type: 'News Article', url: 'https://www.rediff.com/netguide/2000/may/11love.htm' },
        { title: 'India Today (June 2001 retrospective)', type: 'News Article', url: 'https://www.indiatoday.in/magazine/science-and-technology/story/20010618-it-under-siege-as-net-terrorism-becomes-order-of-the-day-773887-2001-06-18' },
        { title: 'Pakistani hackers deface Indian sites', type: 'News Article', url: 'https://www.zdnet.com/article/pakistani-hackers-deface-indian-sites/' },
        { title: 'Hackers hit Indian Railways website', type: 'News Article', url: 'https://timesofindia.indiatimes.com/tech/news/hackers-hit-indian-railways-website/articleshow/32733979.cms' },
        { title: 'India\'s foreign ministry web site hacked', type: 'News Article', url: 'https://www.theguardian.com/technology/2002/feb/11/internetnews.india' },
        { title: 'Police slap sedition charge on hackers', type: 'News Article', url: 'https://timesofindia.indiatimes.com/city/mumbai/police-slap-sedition-charge-on-hackers/articleshow/1344406203.cms' },
        { title: 'Parliament attack: cyber forensics role', type: 'News Article', url: 'https://www.rediff.com/news/2002/mar/01parl10.htm' },
        { title: 'Bugbear Worm Spreads Rapidly (BBC News, Oct 2002)', type: 'News Article', url: 'http://news.bbc.co.uk/2/hi/technology/2292771.stm' },
        { title: 'India, Pak locked in cyber war (Times of India, Nov 2003)', type: 'News Article', url: 'https://timesofindia.indiatimes.com/india/india-pak-locked-in-cyber-war/articleshow/282433.cms' },
        { title: 'Now, viruses target ATMs (Times of India, Dec 2003)', type: 'News Article', url: 'https://timesofindia.indiatimes.com/india/now-viruses-target-atms/articleshow/384777.cms' },
        { title: 'When worms strike (Times of India, Sep 2003)', type: 'News Article', url: 'https://timesofindia.indiatimes.com/india/when-worms-strike/articleshow/183204.cms' },
        { title: 'Sasser worm hits up to 1m computers (The Guardian)', type: 'News Article', url: 'https://www.theguardian.com/technology/2004/may/03/internetnews.internationalnews' },
        { title: 'BPO fraud: another Rs 38 lakh traced | Pune News', type: 'News Article', url: 'https://timesofindia.indiatimes.com/city/pune/bpo-fraud-another-rs-38-lakh-traced/articleshow/1150493.cms' },
        { title: 'Pune call centre fraud rattles India\'s booming BPO sector', type: 'News Article', url: 'https://www.indiatoday.in/magazine/nation/story/20050704-pune-call-centre-fraud-rattles-indias-booming-bpo-sector-raises-questions-on-security-787834-2005-07-04' },
        { title: '400 Indian websites came under attack in Dec - The Economic Times', type: 'News Article', url: 'https://economictimes.indiatimes.com/news/politics-and-nation/400-indian-websites-came-under-attack-in-dec/articleshow/1360699.cms' },
        { title: 'BPO fraud unearthed at SlashSupport - Times of India', type: 'News Article', url: 'https://timesofindia.indiatimes.com/city/chennai/bpo-fraud-unearthed-at-slashsupport/articleshow/1480116.cms' },
        { title: 'Fraud arrest at HSBC\'s Indian call centre | Money - The Guardian', type: 'News Article', url: 'https://www.theguardian.com/money/2006/jun/10/scamsandfraud.crime' },
    ],
  },
  {
    name: 'Research & Academic',
    description: 'Academic institutions and security research organizations',
    icon: Beaker,
    sources: [
        { title: 'Trend Micro Report on Operation Castling', type: 'Research Paper', url: 'https://www.trendmicro.com/vinfo/us/security/news/cyber-attacks/operation-castling-exploring-a-cyber-espionage-campaign-using-the-windigo-malware-family' },
        { title: 'Resecurity Report on Donut', type: 'Research Paper', url: 'https://www.resecurity.com/blog/article/donut-a-new-malware-strain-targeting-indian-government-and-defense-organizations' },
        { title: 'Tracking GhostNet Report Summary', type: 'Research Paper', url: 'https://www.f-secure.com/en/consulting/our-thinking/ghostnet' },
        { title: 'ILOVEYOU (Wikipedia entry)', type: 'Research Paper', url: 'https://en.wikipedia.org/wiki/ILOVEYOU' },
        { title: 'The Spread of the Code-Red Worm (CAIDA)', type: 'Research Paper', url: 'https://www.caida.org/publications/papers/2002/codered/' },
        { title: 'The Nimda Worm: An Overview (SANS Institute)', type: 'Research Paper', url: 'https://www.sans.org/white-papers/195/' },
        { title: 'Demystifying Data Breaches in India (Centre for Internet and Society)', type: 'Research Paper', url: 'https://cis-india.org/internet-governance/blog/demystifying-data-breaches-in-india' },
        { title: '20 Recent Cyber Attacks in India [2025] - Eventus Security', type: 'Research Paper', url: 'https://eventussecurity.com/cybersecurity/india/cyber-attacks/' },
        { title: 'The Nyxem Email Virus: Analysis and Inferences - CAIDA.org', type: 'Research Paper', url: 'https://www.caida.org/publications/papers/2006/nyxem/' },
        { title: 'SQL Slammer (Wikipedia)', type: 'Research Paper', url: 'https://en.wikipedia.org/wiki/SQL_Slammer_worm'},
        { title: 'Blaster (computer worm) (Wikipedia)', type: 'Research Paper', url: 'https://en.wikipedia.org/wiki/Blaster_(computer_worm)'},
        { title: 'Sobig (Wikipedia)', type: 'Research Paper', url: 'https://en.wikipedia.org/wiki/Sobig'},
        { title: 'Mydoom (Wikipedia)', type: 'Research Paper', url: 'https://en.wikipedia.org/wiki/Mydoom'},
        { title: 'Sasser (computer worm) (Wikipedia)', type: 'Research Paper', url: 'https://en.wikipedia.org/wiki/Sasser_(computer_worm)'},
        { title: 'Zotob (computer worm) - Wikipedia', type: 'Research Paper', url: 'https://en.wikipedia.org/wiki/Zotob'},
        { title: 'Kama Sutra (computer worm) - Wikipedia', type: 'Research Paper', url: 'https://en.wikipedia.org/wiki/Kama_Sutra_(computer_worm)'},
    ],
  },
  {
    name: 'Corporate & Vendor Reports',
    description: 'Disclosures from companies and security vendors',
    icon: Briefcase,
    sources: [
        { title: 'Zomato Blog Post on Breach', type: 'Company Disclosure', url: 'https://www.zomato.com/blog/security-update-may-2017' },
    ],
  },
  {
    name: 'Legal & Court Documents',
    description: 'Official court filings and legal records',
    icon: Scale,
    sources: [
        { title: 'National Association Of Software And ... vs Ajay Sood And Ors. on 23 March, 2005', type: 'Court Filing', url: 'https://indiankanoon.org/doc/1143357/' },
        { title: 'Suhas Katti v. Tamil Nadu (Wikipedia)', type: 'Court Filing', url: 'https://en.wikipedia.org/wiki/Suhas_Katti_v._State_of_Tamil_Nadu' },
    ],
  },
];
